apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: azbalancers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                namespace:
                  type: string
  scope: Namespaced
  names:
    plural: azbalancers
    singular: azbalancer
    kind: AZBalancer
    shortNames:
    - azb