apiVersion: v1
kind: ServiceAccount
metadata:
  name: az-balancer-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: az-balancer-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["example.com"]
  resources: ["azbalancers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: az-balancer-operator
subjects:
- kind: ServiceAccount
  name: az-balancer-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: az-balancer-operator
  apiGroup: rbac.authorization.k8s.io